CREATE DATABASE IF NOT EXISTS BANKING;
USE BANKING;



CREATE TABLE CUSTOMERS(
ID INT AUTO_INCREMENT PRIMARY KEY,
CUST_NAME VARCHAR(50),
EMAIL VARCHAR(50),
PHONE VARCHAR(15),
ADDRESS VARCHAR(100)
);

CREATE TABLE ACCOUNTS(
ACC_ID INT AUTO_INCREMENT PRIMARY KEY,
ID INT,
ACCOUNT_TYPE VARCHAR(50),
BALANCE DECIMAL(10,2),
FOREIGN KEY(ID) REFERENCES CUSTOMERS(ID)
);

CREATE TABLE TRANSACTIONS(
TRANS_ID INT AUTO_INCREMENT PRIMARY KEY,
ACCOUNT_ID INT,
TYPE VARCHAR(20),
AMOUNT DECIMAL(10,2)
);

INSERT INTO CUSTOMERS(CUST_NAME,EMAIL,PHONE,ADDRESS)
VALUES
('Piyush', 'piyush@gmail.com', '7412589632', 'Delhi'),
('Dev','dev@gmail.com','8952666632','PUNE');

INSERT INTO ACCOUNTS (ID, ACCOUNT_TYPE, BALANCE)
VALUES 
(1, 'Savings', 5000.00),
(1, 'Current', 2000.00),
(2, 'Savings', 10000.00);

INSERT INTO TRANSACTIONS (ACCOUNT_ID, TYPE , AMOUNT)
VALUES 
(1, 'Deposit', 2000.00),
(1, 'Withdrawal', 1000.00),
(3, 'Deposit', 5000.00);

SELECT * FROM TRANSACTIONS;