CREATE DATABASE STUDENT;
USE STUDENT;
CREATE TABLE STUDETNT_DATA(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL);

RENAME TABLE STUDETNT_DATA TO STUDENT;
INSERT INTO STUDENT VALUES(1, "AMIT", 23);
INSERT INTO STUDENT VALUES(2, "SANJEEV",22);
INSERT INTO STUDENT VALUES(3, "Arya",17);

SELECT * FROM STUDENT;




